name: PR-Branch-Cleanup

on:
  workflow_dispatch:
  pull_request:
    branches: [ Development ]
    paths: Source/**
    types: [closed]
    

jobs:
  cleanup:
    if: github.event.pull_request.merged == 'true'

    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: test-branch-${{ github.event.inputs.target_branch }}-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}
