# This is a basic workflow to help you get started with Actions

name: Build-PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the test-gh-actions branch
on:
  pull_request:
    branches: [ test-gh-actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: prepare rebuild
        run: |
          wget https://www.nuget.org/api/v2/package/Krafs.Rimworld.Ref/1.2.2753
          unzip 1.2.2753 -d reference
      - name: build
        run: python3 Make.py --all-libs --reference reference/ref/net472/
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: test-branch-${{ github.run_number }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rebuild Assembly
          branch: test-branch-${{ github.run_number }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The testing branch for this PR is test-branch-${{ github.run_number }}
          
