name: .NET Core

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ change-shield-belts ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      run: echo `mono --version`
      
